# Stage 1: Install dependencies
FROM node:20.10-alpine AS deps
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm ci

# Stage 2: Build the application
FROM node:20.10-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build the Next.js application
RUN npm run build

# Stage 3: Prepare production image
FROM node:20.10-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
# Create a non-root user
RUN addgroup -S nextjs && adduser -S nextjs -G nextjs

# Copy necessary files
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

USER nextjs

EXPOSE 3000
CMD ["npm", "start"]
